In [2]:
import numpy as np
import sys

In [4]:
# Basic np array initialization
print(np.array([1,2,3,4], dtype=float))
print(np.arange(1,5, dtype=float))
print(np.linspace(1, 4, num=4, dtype=float))
np.empty(4)
np.full(4,4)

[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


array([4, 4, 4, 4])

In [40]:
# Difference between list and NumPy
# List can store various data types in a list, while np array cannot
# Numpy array takes up less space and its faster

%time np.arange(100000)
%time [i for i in range(100000)]

# Matrix
temp_array = np.array([[1,2,3,4],[5,6,7,8]])

CPU times: user 173 µs, sys: 45 µs, total: 218 µs
Wall time: 198 µs
CPU times: user 3.58 ms, sys: 528 µs, total: 4.11 ms
Wall time: 4.12 ms


In [49]:
# Size of the np array
print(temp_array.size)
print(temp_array.ndim)
print(temp_array.shape[1])

8
2
4


In [56]:
temp_array.reshape(8,1)
# Transpose
temp_array.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [71]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,2,2],[3,3,3]])

print(a*b.T)
print(np.matmul(a,b))

[[ 2  6]
 [ 6 12]
 [10 18]]
[[ 8  8  8]
 [18 18 18]
 [28 28 28]]


In [109]:
# Simple Calculations
print(a)
a + 3
a - 3

[[1 2]
 [3 4]
 [5 6]]


array([[-2, -1],
       [ 0,  1],
       [ 2,  3]])

In [129]:
# Useful operations
a.max()
a.min()
a.sum()
a.flatten()

b = np.array([0, 3, 2, 0, 2, 5, 1, 2])
np.unique(b)
np.flip(b)


array([2, 1, 5, 2, 0, 2, 3, 0])